powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3axxpycz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3axy2xca -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3axy59qq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3axybzc9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1sxw93 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1t60s2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1tf2xr -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1th3oy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1ti4lj -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1tmlnx -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1tujbb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1u19cq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1zds35 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1zf613 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b1zgjak -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b21fdxv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2268k2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b23zvvk -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2419to -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b242nwg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2441yo -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b245f7o -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b246cej -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b24lqy8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b24mtn0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b24ngmq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b24nzvy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b24q1s3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b24t1q0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b255faj -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b259hxb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b25aphy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b25b49m -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b25bld2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b25i4t4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b25v0de -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b25w7jn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b25ynqz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b260uto -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b260ycf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b267n1r -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b26kzqe -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b26m7y8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b26nq8p -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b26q74o -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b26q7v5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b26wrae -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b27a8lm -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b27cw0e -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b27hsxj -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b27mw3v -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b27sohw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2814qw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b281cko -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b284juc -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b28aejt -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b28bgi4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b28hily -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b28rid1 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b28rr50 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b28wgz9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b28x855 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b28zhgx -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b296ktn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b29hu2m -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b29icx1 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b29mtw5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b29odcd -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b29sgtf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b29txu3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2a6yfa -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2a7dys -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2a8mrd -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2abu1j -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2ai43t -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2ai6c4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2ayiyd -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2ayy4u -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2az84n -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2b3mjn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2b82ez -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2basln -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2bp8gb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2bpg64 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2bqk0m -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2bufjq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2bzhzp -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2c2fnl -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2cg1v2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2ch8ib -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2ck9sb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2co4bd -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2coma3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2cscwh -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2d5rd5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2d8a3e -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2dbk6y -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3b2deut9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bgceecq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bhlfmpv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bhstw1r -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bn7bhlm -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bn7cdf9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bn7dpu3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bn7f460 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnaunj3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnbxnue -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bncki19 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bncle9j -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bncmajh -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bncnn54 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bncozph -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bncqkq6 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bncrxt8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnd6ssm -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnd831s -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bni0fnd -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bniuqab -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bniw3mc -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnixh42 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnj0io2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnj1ffz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnj2tjg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnj46w7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnjf5a7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnjkyz3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnjlx2n -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnjo5g7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnjr34c -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnjs0b7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnjuaug -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnk9m2k -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnkayyb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnkg21g -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnkgc64 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnkgsw4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnkhvl2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnkmvj5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnkpdcb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnl3o5b -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnlb2ws -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnlcfse -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bnldnbw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo1ddj4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo1es1z -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo1f90r -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo4vkmb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo4x06u -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo601va -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo6snj9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo7t3vw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo7uire -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo7vxyh -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo7y64x -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo7ztxf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo8197t -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo81e04 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo82t5u -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo8fniy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo8jy5b -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo8qbeo -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo8s3om -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo8ua6e -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo8ua9v -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo8vy0m -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo99jxb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo9bpom -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo9de0k -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo9j0x6 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bo9oboq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boa279h -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boa2i5v -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boa38uf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boa3iho -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boa45uv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boa6kzr -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boa8p8r -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boad4bz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boat7dn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boausgh -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boaxhn8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boay0ff -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bob42zf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bob4ljg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bob6ssj -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bobkhin -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bobrh1i -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bobrygb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bobwv28 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bobxd5w -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bobyjb4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3boc7rc6 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3bvnhtsd -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc7x1zb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc7z5jg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc856xb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc85pi8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc89gf0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc8lw5d -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc8tj43 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc8tssn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc94xtv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc95e17 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc9bhmx -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc9hgr3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc9ud0t -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cc9unmu -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cca8jyb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cca8jzm -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccaglb0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccagq1l -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccaq8en -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccawv4a -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccay0ay -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccb768d -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccb8caf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccbesme -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccbf20i -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccbm3my -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccbrcwl -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccbscdy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccc0302 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccc3lvg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccc5px4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cccawx5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccccw8z -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccckx2e -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cccrv7n -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cccyvdi -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccczxps -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccd2baj -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccd4hwl -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccd7qt3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccdgihj -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccdkiyr -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccdqonn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccdzokq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cce2p6b -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccebg75 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cceegn0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccelh7d -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccetk4d -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cceu0nv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cceyeub -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccf58cp -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccf6xoo -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccffgnm -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccfz2o0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccg6xm0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccgd8dr -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccgib7v -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cch0nrv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cch1qfy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cch20vt -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cch9moz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cch9wey -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchau2z -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchau5k -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchcrc2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchd9er -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchdohf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchek37 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchfa8d -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchgm9k -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchhvt2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchizwp -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cchjugb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccmg7ht -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccmghhv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccmgrr8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccmj50a -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccmmbln -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccmmvl0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccmn5qy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccn6fns -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccn8suf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccn9vnw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccnxv0m -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccpaj68 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccpjxeu -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccq016f -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccq1ezh -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccq20dr -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccqke5u -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccrt054 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccry4s2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccs153e -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccwi8vd -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccwxz0j -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccx8uvs -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccy2koo -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccy2ya6 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccy7eup -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccy984j -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ccyh4py -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cd0gud7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cd0tmfb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cd0u18b -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cd0u7g9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cd0uazf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3cd0urli -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3d1hewtn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3d1hhr41 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3f2we5fc -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3l4zwsi9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3lnl8j7m -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3lnpy6l3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3loqoxsw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3lqc3hvg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3lqcz1sw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3n5fw295 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3pdwxno7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3qhtfrn7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3t9q5duu -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3ygtqy6z -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3yih664t -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3yjt5q2l -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/3yo4u8tw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dxpm5b -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dxpon7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dxwiax -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dy0fkt -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dyp1c8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dyqurs -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dz1hs3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dz78jr -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dz9pfu -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dzfbu4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dzkmd9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dzmmll -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dzqqd9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dzr61z -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45dzywdf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e01hpg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e0cnri -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e0pc14 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e0pvtt -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e0qm75 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e0r0yu -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e0t1dt -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e0ub9g -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e15ohf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e1gibq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e1hc7s -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e1mmkq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e1vxv4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45e28o7c -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45ezqrqp -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45gjwbzy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45gkdjdl -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45oq5mvu -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/45xdujq8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/460mhjpc -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/461s4e62 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/471s1gn0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/472ya54j -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/472ya64z -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/47ms1y2a -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485ndo4o -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485p0zir -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485pc2x5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485t2kfb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485ty2l8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485u2cl5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485ukh73 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485uunzr -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485v53za -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485vyrbg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485vzumu -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485wn5b8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485x1zlr -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485xfwyb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485xo51t -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485xydur -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485ytt0m -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485z897u -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/485zog6x -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48600p4k -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48605mzz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4860mfj1 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4860u9fn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48612888 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4861z1w5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48621iqz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4862spd2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4863428c -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48637zyy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4863m9ag -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48644gag -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48648rxl -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4864ui2z -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48654jdq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486593xq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4865l1ty -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4865u0eh -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4865z103 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4866frb3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4866rgro -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4866sbze -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4866yf0w -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48679xrg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4867t5so -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48683sb0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486849le -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4868bt74 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4868bwpf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48699hmw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4869jxqs -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/4869zc7d -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486a8hwx -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486aj025 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486as55d -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486avm26 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486b8axh -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486b96hg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486bkx84 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486bquf8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486cgzsm -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486d0bpt -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486d5lrk -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486d6wps -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486dm88f -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486dqqzx -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486dz2rq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486edwhk -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486er7j7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486fai7f -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486fl7qb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486fni74 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486fp0yo -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486fz9gg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486g5rob -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486gj8ye -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486gqbz5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486gvlgg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486gzv5j -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486hakd3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486hjxtw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486hlhk2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486hnutf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486i4ilo -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486i4j57 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486ihvtw -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486ilsnz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486ipsn7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486j0hu9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486j0z53 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486j4e81 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486jh6fo -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486jpro8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486jrh2c -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486jui19 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486juo8s -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486keboq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486kihe3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486kkqjq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486ko11w -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486koeuf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486kve5t -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486l8hkg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486lj9ht -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486ln9gs -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486lq2gt -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486m1w5e -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486mmu73 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486mqw8x -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486mui34 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486n3m1i -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486nivhq -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486nlxx4 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486on41w -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486otazj -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486po5um -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486q9pgg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486qk5h6 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/486qq9pg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/48few5dg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams-a.deloitte.be/Sites/49s8pl2a -CheckoutRequired $false