powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3nfxhdg1 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ny2s71i -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3q3l6ywf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3wh9w2cs -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3y46goaz -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3y56d2um -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3y5e44wv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3y5fepx2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3y8haqd0 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3yea976f -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3yedzzjk -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3yf9r1nf -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3yfnj0eo -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ygz1bmb -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztun4dg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztun8j8 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztuned9 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztv4vl5 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztv7sab -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztvaptv -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztvc00o -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztvekua -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztvekw1 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/3ztvlidu -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/41uhipnk -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/41vmpla2 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/41vn1dpn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/439whnsc -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45nctf1n -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45nknwup -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45opkr2w -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45p4wlew -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45qmxghh -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45we9ylm -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45x5ybb3 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45xdcyh7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45xwz3v7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/45yu0hvy -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/46su2lic -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/47ftrjxj -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/47ufq7c7 -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/47yn0krg -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/47yo05ab -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/4843r4fn -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/49ap386s -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/49jjdrfk -CheckoutRequired $false
powershell.exe -command ".\SetRequiredCheckout.ps1 -SiteUrl https://edreams4-t.be.deloitte.com/Sites/49jwkp3j -CheckoutRequired $false